name: saropt-dl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - opencv-python
      - rasterio
      - optuna

